import { Prisma } from '@prisma/client';
import { UserService } from './user/user.service';
import { DatabaseService } from './database/database.service';

const databaseService = new DatabaseService();
const userService = new UserService(databaseService);

async function main() {
    const users: Prisma.UserCreateInput[] = [
        {
          id: 'E01',
          name: 'John Doe',
          role: 'Role1',
          password: 'password1',
          dob: '1990-01-01',
          telephone: '1234567890',
          gender: 'Male',
          address: '123 Main St',
          email: 'john.doe@example.com',
        },
        {
          id: 'E02',
          name: 'Jane Smith',
          role: 'Role2',
          password: 'password2',
          dob: '1991-02-02',
          telephone: '0987654321',
          gender: 'Female',
          address: '456 Elm St',
          email: 'jane.smith@example.com',
        },
        {
          id: 'E03',
          name: 'Michael Johnson',
          role: 'Role3',
          password: 'password3',
          dob: '1992-03-03',
          telephone: '1234567891',
          gender: 'Male',
          address: '789 Oak St',
          email: 'michael.johnson@example.com',
        },
        {
          id: 'E04',
          name: 'Emily Davis',
          role: 'Role4',
          password: 'password4',
          dob: '1993-04-04',
          telephone: '1234567892',
          gender: 'Female',
          address: '101 Pine St',
          email: 'emily.davis@example.com',
        },
        {
          id: 'E05',
          name: 'David Wilson',
          role: 'Role5',
          password: 'password5',
          dob: '1994-05-05',
          telephone: '1234567893',
          gender: 'Male',
          address: '202 Maple St',
          email: 'david.wilson@example.com',
        },
        {
          id: 'E06',
          name: 'Sophia Martinez',
          role: 'Role6',
          password: 'password6',
          dob: '1995-06-06',
          telephone: '1234567894',
          gender: 'Female',
          address: '303 Cedar St',
          email: 'sophia.martinez@example.com',
        },
        {
          id: 'E07',
          name: 'James Anderson',
          role: 'Role7',
          password: 'password7',
          dob: '1996-07-07',
          telephone: '1234567895',
          gender: 'Male',
          address: '404 Birch St',
          email: 'james.anderson@example.com',
        },
        {
          id: 'E08',
          name: 'Olivia Thomas',
          role: 'Role8',
          password: 'password8',
          dob: '1997-08-08',
          telephone: '1234567896',
          gender: 'Female',
          address: '505 Walnut St',
          email: 'olivia.thomas@example.com',
        },
        {
          id: 'E09',
          name: 'William Taylor',
          role: 'Role9',
          password: 'password9',
          dob: '1998-09-09',
          telephone: '1234567897',
          gender: 'Male',
          address: '606 Chestnut St',
          email: 'william.taylor@example.com',
        },
        {
          id: 'E10',
          name: 'Ava Lee',
          role: 'Role10',
          password: 'password10',
          dob: '1999-10-10',
          telephone: '1234567898',
          gender: 'Female',
          address: '707 Spruce St',
          email: 'ava.lee@example.com',
        },
        {
          id: 'E11',
          name: 'Alexander Harris',
          role: 'Role11',
          password: 'password11',
          dob: '1990-11-11',
          telephone: '1234567899',
          gender: 'Male',
          address: '808 Fir St',
          email: 'alexander.harris@example.com',
        },
        {
          id: 'E12',
          name: 'Isabella Clark',
          role: 'Role12',
          password: 'password12',
          dob: '1991-12-12',
          telephone: '1234567800',
          gender: 'Female',
          address: '909 Redwood St',
          email: 'isabella.clark@example.com',
        },
        {
          id: 'E13',
          name: 'Daniel Lewis',
          role: 'Role13',
          password: 'password13',
          dob: '1992-01-13',
          telephone: '1234567801',
          gender: 'Male',
          address: '1010 Cypress St',
          email: 'daniel.lewis@example.com',
        },
        {
          id: 'E14',
          name: 'Mia Walker',
          role: 'Role14',
          password: 'password14',
          dob: '1993-02-14',
          telephone: '1234567802',
          gender: 'Female',
          address: '1111 Palm St',
          email: 'mia.walker@example.com',
        },
        {
          id: 'E15',
          name: 'Matthew Hall',
          role: 'Role15',
          password: 'password15',
          dob: '1994-03-15',
          telephone: '1234567803',
          gender: 'Male',
          address: '1212 Magnolia St',
          email: 'matthew.hall@example.com',
        },
        {
          id: 'E16',
          name: 'Amelia Allen',
          role: 'Role16',
          password: 'password16',
          dob: '1995-04-16',
          telephone: '1234567804',
          gender: 'Female',
          address: '1313 Willow St',
          email: 'amelia.allen@example.com',
        },
        {
          id: 'E17',
          name: 'Joseph Young',
          role: 'Role17',
          password: 'password17',
          dob: '1996-05-17',
          telephone: '1234567805',
          gender: 'Male',
          address: '1414 Poplar St',
          email: 'joseph.young@example.com',
        },
        {
          id: 'E18',
          name: 'Charlotte King',
          role: 'Role18',
          password: 'password18',
          dob: '1997-06-18',
          telephone: '1234567806',
          gender: 'Female',
          address: '1515 Ash St',
          email: 'charlotte.king@example.com',
        },
        {
          id: 'E19',
          name: 'Benjamin Wright',
          role: 'Role19',
          password: 'password19',
          dob: '1998-07-19',
          telephone: '1234567807',
          gender: 'Male',
          address: '1616 Beech St',
          email: 'benjamin.wright@example.com',
        },
        {
          id: 'E20',
          name: 'Harper Scott',
          role: 'Role20',
          password: 'password20',
          dob: '1999-08-20',
          telephone: '1234567808',
          gender: 'Female',
          address: '1717 Cedar St',
          email: 'harper.scott@example.com',
        },
        {
          id: 'E21',
          name: 'Lucas Green',
          role: 'Role21',
          password: 'password21',
          dob: '1990-09-21',
          telephone: '1234567809',
          gender: 'Male',
          address: '1818 Pine St',
          email: 'lucas.green@example.com',
        },
        {
          id: 'E22',
          name: 'Evelyn Adams',
          role: 'Role22',
          password: 'password22',
          dob: '1991-10-22',
          telephone: '1234567810',
          gender: 'Female',
          address: '1919 Maple St',
          email: 'evelyn.adams@example.com',
        },
        {
          id: 'E23',
          name: 'Henry Baker',
          role: 'Role23',
          password: 'password23',
          dob: '1992-11-23',
          telephone: '1234567811',
          gender: 'Male',
          address: '2020 Oak St',
          email: 'henry.baker@example.com',
        },
        {
          id: 'E24',
          name: 'Abigail Gonzalez',
          role: 'Role24',
          password: 'password24',
          dob: '1993-12-24',
          telephone: '1234567812',
          gender: 'Female',
          address: '2121 Elm St',
          email: 'abigail.gonzalez@example.com',
        },
        {
          id: 'E25',
          name: 'Sebastian Perez',
          role: 'Role25',
          password: 'password25',
          dob: '1994-01-25',
          telephone: '1234567813',
          gender: 'Male',
          address: '2222 Birch St',
          email: 'sebastian.perez@example.com',
        },
        {
          id: 'E26',
          name: 'Ella Roberts',
          role: 'Role26',
          password: 'password26',
          dob: '1995-02-26',
          telephone: '1234567814',
          gender: 'Female',
          address: '2323 Walnut St',
          email: 'ella.roberts@example.com',
        },
        {
          id: 'E27',
          name: 'Jack Turner',
          role: 'Role27',
          password: 'password27',
          dob: '1996-03-27',
          telephone: '1234567815',
          gender: 'Male',
          address: '2424 Chestnut St',
          email: 'jack.turner@example.com',
        },
        {
          id: 'E28',
          name: 'Grace Phillips',
          role: 'Role28',
          password: 'password28',
          dob: '1997-04-28',
          telephone: '1234567816',
          gender: 'Female',
          address: '2525 Spruce St',
          email: 'grace.phillips@example.com',
        },
        {
          id: 'E29',
          name: 'Aiden Campbell',
          role: 'Role29',
          password: 'password29',
          dob: '1998-05-29',
          telephone: '1234567817',
          gender: 'Male',
          address: '2626 Fir St',
          email: 'aiden.campbell@example.com',
        },
        {
          id: 'E30',
          name: 'Chloe Parker',
          role: 'Role30',
          password: 'password30',
          dob: '1999-06-30',
          telephone: '1234567818',
          gender: 'Female',
          address: '2727 Redwood St',
          email: 'chloe.parker@example.com',
        },
        {
          id: 'E31',
          name: 'Liam Evans',
          role: 'Role31',
          password: 'password31',
          dob: '1990-07-31',
          telephone: '1234567819',
          gender: 'Male',
          address: '2828 Cypress St',
          email: 'liam.evans@example.com',
        },
        {
          id: 'E32',
          name: 'Sofia Edwards',
          role: 'Role32',
          password: 'password32',
          dob: '1991-08-01',
          telephone: '1234567820',
          gender: 'Female',
          address: '2929 Palm St',
          email: 'sofia.edwards@example.com',
        },
        {
          id: 'E33',
          name: 'Mason Collins',
          role: 'Role33',
          password: 'password33',
          dob: '1992-09-02',
          telephone: '1234567821',
          gender: 'Male',
          address: '3030 Magnolia St',
          email: 'mason.collins@example.com',
        },
        {
          id: 'E34',
          name: 'Avery Stewart',
          role: 'Role34',
          password: 'password34',
          dob: '1993-10-03',
          telephone: '1234567822',
          gender: 'Female',
          address: '3131 Willow St',
          email: 'avery.stewart@example.com',
        },
        {
          id: 'E35',
          name: 'Ethan Morris',
          role: 'Role35',
          password: 'password35',
          dob: '1994-11-04',
          telephone: '1234567823',
          gender: 'Male',
          address: '3232 Poplar St',
          email: 'ethan.morris@example.com',
        },
        {
          id: 'E36',
          name: 'Lily Rogers',
          role: 'Role36',
          password: 'password36',
          dob: '1995-12-05',
          telephone: '1234567824',
          gender: 'Female',
          address: '3333 Ash St',
          email: 'lily.rogers@example.com',
        },
        {
          id: 'E37',
          name: 'Logan Reed',
          role: 'Role37',
          password: 'password37',
          dob: '1996-01-06',
          telephone: '1234567825',
          gender: 'Male',
          address: '3434 Beech St',
          email: 'logan.reed@example.com',
        },
        {
          id: 'E38',
          name: 'Zoe Cook',
          role: 'Role38',
          password: 'password38',
          dob: '1997-02-07',
          telephone: '1234567826',
          gender: 'Female',
          address: '3535 Cedar St',
          email: 'zoe.cook@example.com',
        },
        {
          id: 'E39',
          name: 'Lucas Bell',
          role: 'Role39',
          password: 'password39',
          dob: '1998-03-08',
          telephone: '1234567827',
          gender: 'Male',
          address: '3636 Pine St',
          email: 'lucas.bell@example.com',
        },
        {
          id: 'E40',
          name: 'Aria Murphy',
          role: 'Role40',
          password: 'password40',
          dob: '1999-04-09',
          telephone: '1234567828',
          gender: 'Female',
          address: '3737 Maple St',
          email: 'aria.murphy@example.com',
        },
        {
          id: 'E41',
          name: 'Jackson Bailey',
          role: 'Role41',
          password: 'password41',
          dob: '1990-05-10',
          telephone: '1234567829',
          gender: 'Male',
          address: '3838 Oak St',
          email: 'jackson.bailey@example.com',
        },
        {
          id: 'E42',
          name: 'Ella Rivera',
          role: 'Role42',
          password: 'password42',
          dob: '1991-06-11',
          telephone: '1234567830',
          gender: 'Female',
          address: '3939 Elm St',
          email: 'ella.rivera@example.com',
        },
        {
          id: 'E43',
          name: 'Aiden Cooper',
          role: 'Role43',
          password: 'password43',
          dob: '1992-07-12',
          telephone: '1234567831',
          gender: 'Male',
          address: '4040 Birch St',
          email: 'aiden.cooper@example.com',
        },
        {
          id: 'E44',
          name: 'Scarlett Richardson',
          role: 'Role44',
          password: 'password44',
          dob: '1993-08-13',
          telephone: '1234567832',
          gender: 'Female',
          address: '4141 Walnut St',
          email: 'scarlett.richardson@example.com',
        },
        {
          id: 'E45',
          name: 'Henry Cox',
          role: 'Role45',
          password: 'password45',
          dob: '1994-09-14',
          telephone: '1234567833',
          gender: 'Male',
          address: '4242 Chestnut St',
          email: 'henry.cox@example.com',
        },
        {
          id: 'E46',
          name: 'Victoria Howard',
          role: 'Role46',
          password: 'password46',
          dob: '1995-10-15',
          telephone: '1234567834',
          gender: 'Female',
          address: '4343 Spruce St',
          email: 'victoria.howard@example.com',
        },
        {
          id: 'E47',
          name: 'Owen Ward',
          role: 'Role47',
          password: 'password47',
          dob: '1996-11-16',
          telephone: '1234567835',
          gender: 'Male',
          address: '4444 Fir St',
          email: 'owen.ward@example.com',
        },
        {
          id: 'E48',
          name: 'Grace Torres',
          role: 'Role48',
          password: 'password48',
          dob: '1997-12-17',
          telephone: '1234567836',
          gender: 'Female',
          address: '4545 Redwood St',
          email: 'grace.torres@example.com',
        },
        {
          id: 'E49',
          name: 'Liam Peterson',
          role: 'Role49',
          password: 'password49',
          dob: '1998-01-18',
          telephone: '1234567837',
          gender: 'Male',
          address: '4646 Cypress St',
          email: 'liam.peterson@example.com',
        },
        {
          id: 'E50',
          name: 'Avery Gray',
          role: 'Role50',
          password: 'password50',
          dob: '1999-02-19',
          telephone: '1234567838',
          gender: 'Female',
          address: '4747 Palm St',
          email: 'avery.gray@example.com',
        },
      ];

  try {
    for (const user of users) {
      await userService.create(user);
    }
    console.log('Users created successfully.');
  } catch (error) {
    console.error('Error creating users:', error);
  } finally {
    await databaseService.$disconnect();
  }
}

main();
