import { Prisma } from '@prisma/client';
import { UserService } from './user/user.service';
import { DatabaseService } from './database/database.service';

const databaseService = new DatabaseService();
const userService = new UserService(databaseService);

async function main() {
    // const users: Prisma.UserCreateInput[] = 
    // [
    //   {
    //     "id": "E001",
    //     "name": "Joseph Kim",
    //     "role": "Kitchen Staff",
    //     "password": "password1",
    //     "dob": "1983-02-15",
    //     "telephone": "4911249283",
    //     "gender": "Female",
    //     "address": "435 Elizabeth Stravenue, Williamsland, CA 32888",
    //     "email": "christianmark@sanders-lopez.com"
    //   },
    //   {
    //     "id": "E002",
    //     "name": "Maria Terry",
    //     "role": "Inventory Manager",
    //     "password": "password2",
    //     "dob": "2001-04-12",
    //     "telephone": "7463087835",
    //     "gender": "Female",
    //     "address": "3259 Kim Keys, West Charlotteborough, LA 26562",
    //     "email": "sandra21@francis.biz"
    //   },
    //   {
    //     "id": "E003",
    //     "name": "Stacey Stephenson",
    //     "role": "QA Engineer",
    //     "password": "password3",
    //     "dob": "1966-03-20",
    //     "telephone": "5923489600",
    //     "gender": "Male",
    //     "address": "36659 Robert Track, Zacharyhaven, NH 55991",
    //     "email": "patrickvazquez@gmail.com"
    //   },
    //   {
    //     "id": "E004",
    //     "name": "Mary Sampson",
    //     "role": "HR Manager",
    //     "password": "password4",
    //     "dob": "2000-08-21",
    //     "telephone": "9457846914",
    //     "gender": "Male",
    //     "address": "63511 Silva Roads Suite 627, West Brentstad, PA 18380",
    //     "email": "juan20@gmail.com"
    //   },
    //   {
    //     "id": "E005",
    //     "name": "Laurie Medina",
    //     "role": "QA Engineer",
    //     "password": "password5",
    //     "dob": "1982-03-31",
    //     "telephone": "9878484628",
    //     "gender": "Female",
    //     "address": "60786 Matthew Dale Apt. 610, Port Kaitlyn, MA 81646",
    //     "email": "robertbaker@yahoo.com"
    //   },
    //   {
    //     "id": "E006",
    //     "name": "Jonathan Jones II",
    //     "role": "HR Manager",
    //     "password": "password6",
    //     "dob": "1970-12-21",
    //     "telephone": "4302513552",
    //     "gender": "Male",
    //     "address": "62599 William Drives, South Martinchester, NJ 61995",
    //     "email": "raymond26@yahoo.com"
    //   },
    //   {
    //     "id": "E007",
    //     "name": "Nina Fuller",
    //     "role": "QA Engineer",
    //     "password": "password7",
    //     "dob": "1992-08-20",
    //     "telephone": "2006980104",
    //     "gender": "Female",
    //     "address": "792 John Manor Suite 212, East Jeremymouth, SC 32526",
    //     "email": "ysalazar@perez.com"
    //   },
    //   {
    //     "id": "E008",
    //     "name": "Jessica Miles",
    //     "role": "Kitchen Staff",
    //     "password": "password8",
    //     "dob": "1982-01-14",
    //     "telephone": "9181744818",
    //     "gender": "Female",
    //     "address": "753 Alyssa Freeway Suite 392, Jessicashire, NE 09690",
    //     "email": "jwebb@mann.info"
    //   },
    //   {
    //     "id": "E009",
    //     "name": "Nicole Miller",
    //     "role": "Kitchen Staff",
    //     "password": "password9",
    //     "dob": "1981-02-18",
    //     "telephone": "5190886341",
    //     "gender": "Female",
    //     "address": "55161 Lindsey Union, East Sandramouth, MI 95907",
    //     "email": "natalie30@elliott.com"
    //   },
    //   {
    //     "id": "E010",
    //     "name": "Larry Bright",
    //     "role": "Kitchen Staff",
    //     "password": "password10",
    //     "dob": "1965-10-17",
    //     "telephone": "3052431757",
    //     "gender": "Male",
    //     "address": "66743 Christine Orchard, Wrightfort, NM 25078",
    //     "email": "amber36@yahoo.com"
    //   },
    //   {
    //     "id": "E011",
    //     "name": "Jennifer Fisher",
    //     "role": "QA Engineer",
    //     "password": "password11",
    //     "dob": "1994-03-05",
    //     "telephone": "4309294386",
    //     "gender": "Male",
    //     "address": "PSC 9160, Box 6932, APO AE 47608",
    //     "email": "jeffery33@hahn-carr.com"
    //   },
    //   {
    //     "id": "E012",
    //     "name": "Ann Schultz",
    //     "role": "Software Engineer",
    //     "password": "password12",
    //     "dob": "2002-10-17",
    //     "telephone": "8102579583",
    //     "gender": "Female",
    //     "address": "6312 Christopher Freeway, Lake Brittany, CT 96743",
    //     "email": "dsanchez@harper.com"
    //   },
    //   {
    //     "id": "E013",
    //     "name": "Mark Walter",
    //     "role": "Inventory Manager",
    //     "password": "password13",
    //     "dob": "1976-11-28",
    //     "telephone": "0376152880",
    //     "gender": "Male",
    //     "address": "90609 Terry Stravenue Suite 316, Websterport, GA 30426",
    //     "email": "heather85@gonzalez.biz"
    //   },
    //   {
    //     "id": "E014",
    //     "name": "Manuel Walter",
    //     "role": "Kitchen Admin",
    //     "password": "password14",
    //     "dob": "1992-05-15",
    //     "telephone": "5850439580",
    //     "gender": "Male",
    //     "address": "08267 Soto Isle Apt. 133, New Coreyberg, CA 24032",
    //     "email": "rhondagoodman@yahoo.com"
    //   },
    //   {
    //     "id": "E015",
    //     "name": "Christopher Oliver III",
    //     "role": "QA Engineer",
    //     "password": "password15",
    //     "dob": "1994-11-28",
    //     "telephone": "3200863374",
    //     "gender": "Male",
    //     "address": "99874 Christopher Track Apt. 412, Port Johnburgh, MS 02630",
    //     "email": "amberfrazier@yahoo.com"
    //   },
    //   {
    //     "id": "E016",
    //     "name": "Steven Banks",
    //     "role": "Kitchen Staff",
    //     "password": "password16",
    //     "dob": "1976-11-11",
    //     "telephone": "4179552857",
    //     "gender": "Female",
    //     "address": "7616 Holly Dale, East Brookestad, NJ 21349",
    //     "email": "pattonjessica@smith.com"
    //   },
    //   {
    //     "id": "E017",
    //     "name": "Tyler Underwood",
    //     "role": "Software Engineer",
    //     "password": "password17",
    //     "dob": "1987-10-08",
    //     "telephone": "7486400454",
    //     "gender": "Male",
    //     "address": "33698 Brian Isle Suite 881, Barnettview, WI 77933",
    //     "email": "carterjoshua@gmail.com"
    //   },
    //   {
    //     "id": "E018",
    //     "name": "James Chavez",
    //     "role": "Kitchen Admin",
    //     "password": "password18",
    //     "dob": "1979-12-25",
    //     "telephone": "1128951107",
    //     "gender": "Male",
    //     "address": "62012 Shah Trafficway, Kellyshire, WY 26945",
    //     "email": "dawn32@simpson.net"
    //   },
    //   {
    //     "id": "E019",
    //     "name": "Linda Hall",
    //     "role": "Kitchen Staff",
    //     "password": "password19",
    //     "dob": "1974-02-01",
    //     "telephone": "1675062918",
    //     "gender": "Female",
    //     "address": "Unit 7266 Box 9622, DPO AE 09111",
    //     "email": "fbanks@parker-brooks.com"
    //   },
    //   {
    //     "id": "E020",
    //     "name": "Anthony Robles",
    //     "role": "HR Manager",
    //     "password": "password20",
    //     "dob": "1985-10-13",
    //     "telephone": "2055719975",
    //     "gender": "Male",
    //     "address": "22371 Natalie View, Deborahberg, OK 51949",
    //     "email": "tyoung@rojas.biz"
    //   },
    //   {
    //     "id": "E021",
    //     "name": "Dr. Jonathan Cunningham",
    //     "role": "Kitchen Admin",
    //     "password": "password21",
    //     "dob": "1984-08-11",
    //     "telephone": "1824746724",
    //     "gender": "Female",
    //     "address": "2523 Robert Square Apt. 218, Port Amystad, SC 03142",
    //     "email": "paigemontgomery@hotmail.com"
    //   },
    //   {
    //     "id": "E022",
    //     "name": "Christina Walsh",
    //     "role": "Software Engineer",
    //     "password": "password22",
    //     "dob": "1986-02-09",
    //     "telephone": "3489052101",
    //     "gender": "Male",
    //     "address": "8661 Amber Crescent Apt. 707, Samuelberg, CA 00752",
    //     "email": "baileyle@hotmail.com"
    //   },
    //   {
    //     "id": "E023",
    //     "name": "Stephen Ellis",
    //     "role": "Kitchen Admin",
    //     "password": "password23",
    //     "dob": "1986-11-01",
    //     "telephone": "0642285152",
    //     "gender": "Male",
    //     "address": "42577 Garrett Route Suite 470, Smithfurt, NM 64550",
    //     "email": "nancygillespie@lee-walter.org"
    //   },
    //   {
    //     "id": "E024",
    //     "name": "Alyssa Kennedy",
    //     "role": "Software Engineer",
    //     "password": "password24",
    //     "dob": "1982-07-18",
    //     "telephone": "7342776367",
    //     "gender": "Male",
    //     "address": "124 Davis Drive Suite 822, North Heatherborough, ND 06559",
    //     "email": "johnsoneric@gonzalez-mueller.net"
    //   },
    //   {
    //     "id": "E025",
    //     "name": "April Murphy",
    //     "role": "Kitchen Admin",
    //     "password": "password25",
    //     "dob": "1991-11-26",
    //     "telephone": "3892510563",
    //     "gender": "Female",
    //     "address": "USNV Simpson, FPO AE 87819",
    //     "email": "lscott@fleming.com"
    //   },
    //   {
    //     "id": "E026",
    //     "name": "Brandi Blake",
    //     "role": "Kitchen Staff",
    //     "password": "password26",
    //     "dob": "2004-06-21",
    //     "telephone": "2989830623",
    //     "gender": "Female",
    //     "address": "4444 Audrey Mission Apt. 266, North Joseborough, AZ 19499",
    //     "email": "lesliemitchell@gmail.com"
    //   },
    //   {
    //     "id": "E027",
    //     "name": "Bailey Wilkinson",
    //     "role": "Software Engineer",
    //     "password": "password27",
    //     "dob": "2004-10-03",
    //     "telephone": "8534838815",
    //     "gender": "Female",
    //     "address": "650 Elliott Light Suite 548, East Christina, FL 75989",
    //     "email": "wilsonmichelle@larson.com"
    //   },
    //   {
    //     "id": "E028",
    //     "name": "Cheryl Wilson",
    //     "role": "Kitchen Staff",
    //     "password": "password28",
    //     "dob": "1980-03-25",
    //     "telephone": "4865092380",
    //     "gender": "Female",
    //     "address": "20952 David Roads Apt. 405, Michaelberg, UT 07100",
    //     "email": "ohawkins@yahoo.com"
    //   },
    //   {
    //     "id": "E029",
    //     "name": "Danielle Donovan",
    //     "role": "Inventory Manager",
    //     "password": "password29",
    //     "dob": "1993-04-21",
    //     "telephone": "9811503685",
    //     "gender": "Male",
    //     "address": "07138 Hopkins Pines Apt. 882, West William, MI 15908",
    //     "email": "wmartin@gmail.com"
    //   },
    //   {
    //     "id": "E030",
    //     "name": "Raymond Jefferson",
    //     "role": "Kitchen Staff",
    //     "password": "password30",
    //     "dob": "1969-09-27",
    //     "telephone": "7247670654",
    //     "gender": "Female",
    //     "address": "PSC 0800, Box 7398, APO AP 84712",
    //     "email": "bruce67@wolfe.com"
    //   },
    //   {
    //     "id": "E031",
    //     "name": "Christian Stark",
    //     "role": "Software Engineer",
    //     "password": "password31",
    //     "dob": "1994-09-28",
    //     "telephone": "4112391866",
    //     "gender": "Male",
    //     "address": "6818 Stephanie Bridge Suite 031, New Sherrimouth, DC 17226",
    //     "email": "juarezjoseph@gmail.com"
    //   },
    //   {
    //     "id": "E032",
    //     "name": "Sarah Baker",
    //     "role": "Kitchen Admin",
    //     "password": "password32",
    //     "dob": "1970-01-19",
    //     "telephone": "9495803955",
    //     "gender": "Male",
    //     "address": "6489 Jennifer Vista, Port Kristaland, MD 54754",
    //     "email": "mccannjuan@cook-peters.com"
    //   },
    //   {
    //     "id": "E033",
    //     "name": "Peter Brown",
    //     "role": "Inventory Manager",
    //     "password": "password33",
    //     "dob": "1982-12-25",
    //     "telephone": "5222902138",
    //     "gender": "Male",
    //     "address": "Unit 9794 Box 8693, DPO AA 63020",
    //     "email": "mooredanielle@middleton.org"
    //   },
    //   {
    //     "id": "E034",
    //     "name": "Nicole Kirby",
    //     "role": "QA Engineer",
    //     "password": "password34",
    //     "dob": "1987-04-14",
    //     "telephone": "3985136549",
    //     "gender": "Female",
    //     "address": "USNV Nichols, FPO AE 90349",
    //     "email": "moorejesus@yahoo.com"
    //   },
    //   {
    //     "id": "E035",
    //     "name": "Isabella Stokes",
    //     "role": "QA Engineer",
    //     "password": "password35",
    //     "dob": "1984-06-14",
    //     "telephone": "3762196438",
    //     "gender": "Female",
    //     "address": "8780 Kathleen Walks, South Christineberg, VA 64365",
    //     "email": "mooneybrian@hotmail.com"
    //   },
    //   {
    //     "id": "E036",
    //     "name": "Rachel Hunt",
    //     "role": "Kitchen Admin",
    //     "password": "password36",
    //     "dob": "1979-09-08",
    //     "telephone": "8561487319",
    //     "gender": "Female",
    //     "address": "0833 Cynthia Port, South Jennifer, NE 11726",
    //     "email": "loveann@matthews.com"
    //   },
    //   {
    //     "id": "E037",
    //     "name": "Christopher Holden",
    //     "role": "Software Engineer",
    //     "password": "password37",
    //     "dob": "1987-05-07",
    //     "telephone": "0340994042",
    //     "gender": "Male",
    //     "address": "6717 Moore Corners, Brownburgh, OH 82848",
    //     "email": "gina86@hart.com"
    //   },
    //   {
    //     "id": "E038",
    //     "name": "Donna Contreras",
    //     "role": "Software Architect",
    //     "password": "password38",
    //     "dob": "1998-02-17",
    //     "telephone": "5960249776",
    //     "gender": "Male",
    //     "address": "7624 Brian Road Suite 539, North Karenburgh, AL 35999",
    //     "email": "youngroy@gmail.com"
    //   },
    //   {
    //     "id": "E039",
    //     "name": "Michael Fletcher",
    //     "role": "Inventory Manager",
    //     "password": "password39",
    //     "dob": "2002-04-05",
    //     "telephone": "1800041542",
    //     "gender": "Male",
    //     "address": "3780 Michele Camp Apt. 512, South Staceyville, OK 94384",
    //     "email": "ellisluis@reese-bradford.com"
    //   },
    //   {
    //     "id": "E040",
    //     "name": "Dr. Dawn Gibson",
    //     "role": "HR Manager",
    //     "password": "password40",
    //     "dob": "1996-01-02",
    //     "telephone": "1091944965",
    //     "gender": "Female",
    //     "address": "PSC 7202, Box 9212, APO AP 20187",
    //     "email": "anthony68@gmail.com"
    //   },
    //   {
    //     "id": "E041",
    //     "name": "Kathleen Stevens",
    //     "role": "HR Manager",
    //     "password": "password41",
    //     "dob": "2003-12-24",
    //     "telephone": "1780755239",
    //     "gender": "Female",
    //     "address": "93832 Tiffany Roads, North Jenniferchester, HI 14386",
    //     "email": "garciakathy@gmail.com"
    //   },
    //   {
    //     "id": "E042",
    //     "name": "Sean Washington",
    //     "role": "Kitchen Staff",
    //     "password": "password42",
    //     "dob": "1990-07-08",
    //     "telephone": "6053650951",
    //     "gender": "Male",
    //     "address": "33117 Hughes Spring Apt. 102, East Susan, FL 38890",
    //     "email": "duncanchristopher@hawkins-lamb.com"
    //   },
    //   {
    //     "id": "E043",
    //     "name": "Timothy Romero",
    //     "role": "HR Manager",
    //     "password": "password43",
    //     "dob": "1982-04-02",
    //     "telephone": "6814258004",
    //     "gender": "Male",
    //     "address": "186 Thomas Mission, Campbellburgh, WI 21988",
    //     "email": "oparker@gmail.com"
    //   },
    //   {
    //     "id": "E044",
    //     "name": "Derrick Kelley",
    //     "role": "Kitchen Staff",
    //     "password": "password44",
    //     "dob": "1994-05-23",
    //     "telephone": "4416526498",
    //     "gender": "Male",
    //     "address": "9152 George Center Suite 807, Lake Reginaldchester, OH 99635",
    //     "email": "patrick00@yahoo.com"
    //   },
    //   {
    //     "id": "E045",
    //     "name": "Anne Leonard",
    //     "role": "QA Engineer",
    //     "password": "password45",
    //     "dob": "2002-02-24",
    //     "telephone": "8848804738",
    //     "gender": "Female",
    //     "address": "50953 Ariel Lane, Scotthaven, NV 57121",
    //     "email": "alyssa37@coleman-fernandez.com"
    //   },
    //   {
    //     "id": "E046",
    //     "name": "Tina Johns",
    //     "role": "Software Engineer",
    //     "password": "password46",
    //     "dob": "1998-11-02",
    //     "telephone": "6676572744",
    //     "gender": "Male",
    //     "address": "64054 Daniel Burgs Suite 227, Christinaburgh, WA 44020",
    //     "email": "william94@yahoo.com"
    //   },
    //   {
    //     "id": "E047",
    //     "name": "Keith Wright",
    //     "role": "Kitchen Staff",
    //     "password": "password47",
    //     "dob": "2004-08-30",
    //     "telephone": "6130352562",
    //     "gender": "Female",
    //     "address": "41574 Thornton Ridges Suite 412, Port Ericfurt, MT 90297",
    //     "email": "ginaross@waters.com"
    //   },
    //   {
    //     "id": "E048",
    //     "name": "Jonathan Rich",
    //     "role": "Software Architect",
    //     "password": "password48",
    //     "dob": "1997-12-16",
    //     "telephone": "9757438880",
    //     "gender": "Male",
    //     "address": "554 Romero Highway, Valenciaview, LA 15917",
    //     "email": "ewilson@hotmail.com"
    //   },
    //   {
    //     "id": "E049",
    //     "name": "Anne Peterson",
    //     "role": "Inventory Manager",
    //     "password": "password49",
    //     "dob": "1984-11-02",
    //     "telephone": "7536801736",
    //     "gender": "Female",
    //     "address": "9125 Sampson Track, Bryantland, MN 31819",
    //     "email": "kevin30@cooper-ramirez.info"
    //   },
    //   {
    //     "id": "E050",
    //     "name": "Robert Rodriguez",
    //     "role": "Kitchen Admin",
    //     "password": "password50",
    //     "dob": "1983-04-02",
    //     "telephone": "2797460123",
    //     "gender": "Male",
    //     "address": "750 Walker Turnpike Apt. 948, Port Matthewshire, MS 77609",
    //     "email": "jeansanders@rivera.org"
    //   },
    //   {
    //     "id": "E051",
    //     "name": "Amanda Campbell",
    //     "role": "HR Manager",
    //     "password": "password51",
    //     "dob": "1966-12-09",
    //     "telephone": "6003870397",
    //     "gender": "Female",
    //     "address": "902 Stone Roads, Brendashire, MN 97913",
    //     "email": "erinkelly@stafford-bernard.info"
    //   },
    //   {
    //     "id": "E052",
    //     "name": "Dr. Ryan Parker",
    //     "role": "QA Engineer",
    //     "password": "password52",
    //     "dob": "1978-06-07",
    //     "telephone": "2266025590",
    //     "gender": "Female",
    //     "address": "367 Ellis Cliffs, West Lindashire, GA 71987",
    //     "email": "sanchezwillie@yahoo.com"
    //   },
    //   {
    //     "id": "E053",
    //     "name": "Mrs. Melanie Romero",
    //     "role": "Software Architect",
    //     "password": "password53",
    //     "dob": "1990-03-30",
    //     "telephone": "4461096886",
    //     "gender": "Female",
    //     "address": "4561 Daniels Ville, Katherinechester, UT 75552",
    //     "email": "connor68@murphy-terrell.com"
    //   },
    //   {
    //     "id": "E054",
    //     "name": "Shane Wood",
    //     "role": "Software Engineer",
    //     "password": "password54",
    //     "dob": "1976-10-22",
    //     "telephone": "2694983101",
    //     "gender": "Male",
    //     "address": "263 Brian Skyway, Gabrielbury, NC 69255",
    //     "email": "tashawagner@hotmail.com"
    //   },
    //   {
    //     "id": "E055",
    //     "name": "Denise Hopkins",
    //     "role": "Kitchen Admin",
    //     "password": "password55",
    //     "dob": "1968-08-31",
    //     "telephone": "4640272726",
    //     "gender": "Male",
    //     "address": "9941 Katherine Mountain Suite 368, Gabrielton, VT 94757",
    //     "email": "salinasvalerie@yahoo.com"
    //   },
    //   {
    //     "id": "E056",
    //     "name": "Margaret Atkins",
    //     "role": "Inventory Manager",
    //     "password": "password56",
    //     "dob": "2001-02-21",
    //     "telephone": "8920552139",
    //     "gender": "Male",
    //     "address": "Unit 0245 Box 3543, DPO AP 04562",
    //     "email": "debrameyer@hotmail.com"
    //   },
    //   {
    //     "id": "E057",
    //     "name": "Joshua Becker DDS",
    //     "role": "QA Engineer",
    //     "password": "password57",
    //     "dob": "1997-02-02",
    //     "telephone": "2046603791",
    //     "gender": "Male",
    //     "address": "47759 Valenzuela Rapids, Jeremyfurt, WI 04544",
    //     "email": "hicksstephanie@yahoo.com"
    //   },
    //   {
    //     "id": "E058",
    //     "name": "David Campbell",
    //     "role": "Software Engineer",
    //     "password": "password58",
    //     "dob": "2003-03-01",
    //     "telephone": "7602860577",
    //     "gender": "Female",
    //     "address": "355 Day Camp, North Danielmouth, AZ 07204",
    //     "email": "kristenprice@yahoo.com"
    //   },
    //   {
    //     "id": "E059",
    //     "name": "Michael Burch",
    //     "role": "HR Manager",
    //     "password": "password59",
    //     "dob": "1995-06-03",
    //     "telephone": "4100137657",
    //     "gender": "Male",
    //     "address": "28777 Courtney Highway Apt. 552, Maysview, WY 65840",
    //     "email": "treeves@yang.org"
    //   },
    //   {
    //     "id": "E060",
    //     "name": "Jennifer Rivera",
    //     "role": "Software Engineer",
    //     "password": "password60",
    //     "dob": "1965-05-07",
    //     "telephone": "9612017542",
    //     "gender": "Female",
    //     "address": "41475 Patterson Mountain Apt. 684, East Andreaton, NJ 52101",
    //     "email": "qjones@gmail.com"
    //   },
    //   {
    //     "id": "E061",
    //     "name": "Peter Acosta",
    //     "role": "Kitchen Admin",
    //     "password": "password61",
    //     "dob": "1992-08-20",
    //     "telephone": "2216196634",
    //     "gender": "Female",
    //     "address": "300 Welch Trafficway Suite 551, Lake Wendytown, WV 40851",
    //     "email": "lisa29@gmail.com"
    //   },
    //   {
    //     "id": "E062",
    //     "name": "Amber Stephens",
    //     "role": "Inventory Manager",
    //     "password": "password62",
    //     "dob": "1972-06-21",
    //     "telephone": "2589942763",
    //     "gender": "Male",
    //     "address": "1722 Koch Mission Apt. 675, Buckleyton, DE 75787",
    //     "email": "tommy41@yahoo.com"
    //   },
    //   {
    //     "id": "E063",
    //     "name": "Sarah Morgan",
    //     "role": "Inventory Manager",
    //     "password": "password63",
    //     "dob": "1969-08-09",
    //     "telephone": "9030095516",
    //     "gender": "Male",
    //     "address": "573 Shawn Path, New Heatherbury, NV 47328",
    //     "email": "maryallen@yahoo.com"
    //   },
    //   {
    //     "id": "E064",
    //     "name": "Jaime Brady",
    //     "role": "Kitchen Staff",
    //     "password": "password64",
    //     "dob": "1965-01-27",
    //     "telephone": "5974874528",
    //     "gender": "Female",
    //     "address": "6733 Wagner Trail Suite 019, New Ethanland, RI 13478",
    //     "email": "qday@leonard.org"
    //   },
    //   {
    //     "id": "E065",
    //     "name": "Melissa Barnes",
    //     "role": "Inventory Manager",
    //     "password": "password65",
    //     "dob": "2004-03-12",
    //     "telephone": "3711228547",
    //     "gender": "Male",
    //     "address": "6356 Aaron Spurs Suite 105, New Kimberlyhaven, WI 51118",
    //     "email": "dturner@gmail.com"
    //   },
    //   {
    //     "id": "E066",
    //     "name": "Zachary Hogan",
    //     "role": "Inventory Manager",
    //     "password": "password66",
    //     "dob": "1965-11-05",
    //     "telephone": "3905747567",
    //     "gender": "Female",
    //     "address": "913 Brown Shore, West Hannahburgh, HI 61968",
    //     "email": "paula33@hotmail.com"
    //   },
    //   {
    //     "id": "E067",
    //     "name": "Shannon Hogan",
    //     "role": "Kitchen Staff",
    //     "password": "password67",
    //     "dob": "2000-12-07",
    //     "telephone": "5596036715",
    //     "gender": "Male",
    //     "address": "8286 Rebecca Spur, Traciland, MT 10005",
    //     "email": "wcunningham@moore.com"
    //   },
    //   {
    //     "id": "E068",
    //     "name": "Alexander Anderson",
    //     "role": "Kitchen Staff",
    //     "password": "password68",
    //     "dob": "1971-03-09",
    //     "telephone": "7540001567",
    //     "gender": "Male",
    //     "address": "611 George Views Suite 542, Rodriguezborough, AK 47604",
    //     "email": "jennifer26@perry-ray.info"
    //   },
    //   {
    //     "id": "E069",
    //     "name": "Stephanie Sexton",
    //     "role": "QA Engineer",
    //     "password": "password69",
    //     "dob": "1964-08-05",
    //     "telephone": "6606250176",
    //     "gender": "Female",
    //     "address": "69088 Emily Parkway Suite 144, East Keithfurt, VA 44663",
    //     "email": "sophia42@hotmail.com"
    //   },
    //   {
    //     "id": "E070",
    //     "name": "Richard Pugh",
    //     "role": "QA Engineer",
    //     "password": "password70",
    //     "dob": "1990-01-29",
    //     "telephone": "6951802150",
    //     "gender": "Male",
    //     "address": "USCGC Ortiz, FPO AP 37111",
    //     "email": "waltoncarl@yahoo.com"
    //   },
    //   {
    //     "id": "E071",
    //     "name": "Rebecca Rivas",
    //     "role": "Software Architect",
    //     "password": "password71",
    //     "dob": "1994-03-28",
    //     "telephone": "5593934475",
    //     "gender": "Female",
    //     "address": "533 Michael Common, Rodriguezshire, VA 16649",
    //     "email": "smoore@hotmail.com"
    //   },
    //   {
    //     "id": "E072",
    //     "name": "Lisa Jones",
    //     "role": "Kitchen Admin",
    //     "password": "password72",
    //     "dob": "1965-05-30",
    //     "telephone": "9700609148",
    //     "gender": "Female",
    //     "address": "201 Alicia Junction Suite 689, Lake Alexport, OK 65230",
    //     "email": "ystewart@freeman.com"
    //   },
    //   {
    //     "id": "E073",
    //     "name": "Jamie Jenkins",
    //     "role": "Inventory Manager",
    //     "password": "password73",
    //     "dob": "1996-12-01",
    //     "telephone": "0138635276",
    //     "gender": "Male",
    //     "address": "911 Carter Burgs, West David, MS 77161",
    //     "email": "williamsroy@yahoo.com"
    //   },
    //   {
    //     "id": "E074",
    //     "name": "Jose Johnson",
    //     "role": "Kitchen Staff",
    //     "password": "password74",
    //     "dob": "1967-05-01",
    //     "telephone": "0584801402",
    //     "gender": "Female",
    //     "address": "2271 Lee Ridge, Michaeltown, WA 47222",
    //     "email": "rsmith@graham.com"
    //   },
    //   {
    //     "id": "E075",
    //     "name": "James Oliver",
    //     "role": "Software Architect",
    //     "password": "password75",
    //     "dob": "1990-02-08",
    //     "telephone": "7378819681",
    //     "gender": "Female",
    //     "address": "41866 Samuel Shore Suite 936, New April, PA 86268",
    //     "email": "corey33@orozco-martinez.org"
    //   },
    //   {
    //     "id": "E076",
    //     "name": "Jenna Gilmore",
    //     "role": "Inventory Manager",
    //     "password": "password76",
    //     "dob": "1979-04-30",
    //     "telephone": "2487759754",
    //     "gender": "Female",
    //     "address": "06340 Mendez Hills Suite 373, North Jon, NH 59282",
    //     "email": "amyvillegas@gmail.com"
    //   },
    //   {
    //     "id": "E077",
    //     "name": "Dave Ramos",
    //     "role": "Software Architect",
    //     "password": "password77",
    //     "dob": "2003-08-07",
    //     "telephone": "2243809515",
    //     "gender": "Male",
    //     "address": "PSC 4785, Box 6906, APO AE 26944",
    //     "email": "belltracy@mack.com"
    //   },
    //   {
    //     "id": "E078",
    //     "name": "Logan Holloway",
    //     "role": "Software Engineer",
    //     "password": "password78",
    //     "dob": "1984-01-12",
    //     "telephone": "6194801224",
    //     "gender": "Female",
    //     "address": "556 Stephens Harbor Suite 345, East Kevinborough, MD 83644",
    //     "email": "bryan55@lawson.com"
    //   },
    //   {
    //     "id": "E079",
    //     "name": "Ashley Thomas",
    //     "role": "Kitchen Staff",
    //     "password": "password79",
    //     "dob": "1973-09-11",
    //     "telephone": "3806002097",
    //     "gender": "Male",
    //     "address": "5741 Thomas Spur, Port Marcuston, UT 23341",
    //     "email": "owenpeter@hotmail.com"
    //   },
    //   {
    //     "id": "E080",
    //     "name": "Jason Young",
    //     "role": "Kitchen Staff",
    //     "password": "password80",
    //     "dob": "1990-04-16",
    //     "telephone": "4006342074",
    //     "gender": "Male",
    //     "address": "7281 Baker Mills Apt. 478, Port Katherine, GA 49400",
    //     "email": "david35@yahoo.com"
    //   },
    //   {
    //     "id": "E081",
    //     "name": "Joseph Harmon",
    //     "role": "Kitchen Staff",
    //     "password": "password81",
    //     "dob": "1973-11-21",
    //     "telephone": "2446739996",
    //     "gender": "Male",
    //     "address": "854 Torres Fields, Blakeville, CA 23861",
    //     "email": "cindy03@hebert.net"
    //   },
    //   {
    //     "id": "E082",
    //     "name": "Michael Martinez",
    //     "role": "Software Engineer",
    //     "password": "password82",
    //     "dob": "2001-09-01",
    //     "telephone": "8601094820",
    //     "gender": "Female",
    //     "address": "1760 Riley Tunnel, West Deborahfurt, TX 31861",
    //     "email": "stevensherman@blackwell.net"
    //   },
    //   {
    //     "id": "E083",
    //     "name": "Christina Smith",
    //     "role": "QA Engineer",
    //     "password": "password83",
    //     "dob": "2002-01-04",
    //     "telephone": "7778194927",
    //     "gender": "Female",
    //     "address": "336 Davidson Mountains Apt. 281, Nancyport, PA 72068",
    //     "email": "kathleenperry@gmail.com"
    //   },
    //   {
    //     "id": "E084",
    //     "name": "Michael Vega",
    //     "role": "Software Engineer",
    //     "password": "password84",
    //     "dob": "2003-10-31",
    //     "telephone": "0768854857",
    //     "gender": "Male",
    //     "address": "8523 Bryan Course, Parkville, WI 65338",
    //     "email": "linda35@martinez-campbell.com"
    //   },
    //   {
    //     "id": "E085",
    //     "name": "Gina Vargas",
    //     "role": "Kitchen Admin",
    //     "password": "password85",
    //     "dob": "1969-03-19",
    //     "telephone": "0042260643",
    //     "gender": "Male",
    //     "address": "Unit 9398 Box 4672, DPO AP 31260",
    //     "email": "kristawest@carr.com"
    //   },
    //   {
    //     "id": "E086",
    //     "name": "Michele Sanchez",
    //     "role": "Kitchen Staff",
    //     "password": "password86",
    //     "dob": "1999-12-22",
    //     "telephone": "9260221025",
    //     "gender": "Male",
    //     "address": "275 Green Rue, South Lisa, MS 78268",
    //     "email": "icrawford@gmail.com"
    //   },
    //   {
    //     "id": "E087",
    //     "name": "Emily Parks",
    //     "role": "Kitchen Admin",
    //     "password": "password87",
    //     "dob": "1976-05-29",
    //     "telephone": "8483880419",
    //     "gender": "Female",
    //     "address": "0306 Sean Cove Suite 922, Stewartton, TX 90142",
    //     "email": "bmoore@yahoo.com"
    //   },
    //   {
    //     "id": "E088",
    //     "name": "Lisa Berry",
    //     "role": "Kitchen Admin",
    //     "password": "password88",
    //     "dob": "1971-04-23",
    //     "telephone": "9325597060",
    //     "gender": "Female",
    //     "address": "678 Suarez Plaza Apt. 948, Mitchelltown, PA 97999",
    //     "email": "cevans@yahoo.com"
    //   },
    //   {
    //     "id": "E089",
    //     "name": "Scott Ryan",
    //     "role": "Inventory Manager",
    //     "password": "password89",
    //     "dob": "1974-05-27",
    //     "telephone": "3510314647",
    //     "gender": "Male",
    //     "address": "81358 Crawford Corner Apt. 264, Sarahstad, UT 48813",
    //     "email": "karenscott@turner.info"
    //   },
    //   {
    //     "id": "E090",
    //     "name": "Michael Cruz",
    //     "role": "QA Engineer",
    //     "password": "password90",
    //     "dob": "1974-07-05",
    //     "telephone": "3356406261",
    //     "gender": "Male",
    //     "address": "8618 Jessica Valley, Melodyshire, MN 98105",
    //     "email": "zachary46@smith-james.com"
    //   },
    //   {
    //     "id": "E091",
    //     "name": "Michael Smith",
    //     "role": "Kitchen Staff",
    //     "password": "password91",
    //     "dob": "1979-11-24",
    //     "telephone": "7764585856",
    //     "gender": "Female",
    //     "address": "385 Henry Street, Lukeport, AZ 60282",
    //     "email": "paul31@carter.com"
    //   },
    //   {
    //     "id": "E092",
    //     "name": "Jennifer Wall",
    //     "role": "Kitchen Staff",
    //     "password": "password92",
    //     "dob": "1989-07-11",
    //     "telephone": "7591865665",
    //     "gender": "Male",
    //     "address": "908 Jill Vista Suite 768, West Brianhaven, MS 28775",
    //     "email": "shawnkeller@yahoo.com"
    //   },
    //   {
    //     "id": "E093",
    //     "name": "Michael Sandoval",
    //     "role": "Kitchen Admin",
    //     "password": "password93",
    //     "dob": "1965-07-30",
    //     "telephone": "3602468916",
    //     "gender": "Female",
    //     "address": "296 Martha Trail, North Christine, WY 32222",
    //     "email": "joseph23@kirby.com"
    //   },
    //   {
    //     "id": "E094",
    //     "name": "Rachel Stewart",
    //     "role": "Kitchen Staff",
    //     "password": "password94",
    //     "dob": "1972-07-12",
    //     "telephone": "5709203787",
    //     "gender": "Male",
    //     "address": "USNV Lawrence, FPO AE 62640",
    //     "email": "roydawn@kidd.com"
    //   },
    //   {
    //     "id": "E095",
    //     "name": "Ray Chavez",
    //     "role": "Kitchen Staff",
    //     "password": "password95",
    //     "dob": "1993-05-09",
    //     "telephone": "7288720369",
    //     "gender": "Female",
    //     "address": "Unit 6293 Box 7727, DPO AE 51684",
    //     "email": "courtney48@hotmail.com"
    //   },
    //   {
    //     "id": "E096",
    //     "name": "Jill Peterson",
    //     "role": "Software Architect",
    //     "password": "password96",
    //     "dob": "1989-12-04",
    //     "telephone": "6514050664",
    //     "gender": "Female",
    //     "address": "1921 Daniel Mills, Dawnton, FL 36037",
    //     "email": "uarnold@nunez.biz"
    //   },
    //   {
    //     "id": "E097",
    //     "name": "Brandon Mckenzie",
    //     "role": "Kitchen Staff",
    //     "password": "password97",
    //     "dob": "1984-12-19",
    //     "telephone": "5443290662",
    //     "gender": "Male",
    //     "address": "53229 Williams Track, Kimberlymouth, NJ 21528",
    //     "email": "natashahenry@yahoo.com"
    //   },
    //   {
    //     "id": "E098",
    //     "name": "Michael Robbins",
    //     "role": "Inventory Manager",
    //     "password": "password98",
    //     "dob": "1991-07-27",
    //     "telephone": "7813731729",
    //     "gender": "Female",
    //     "address": "489 Jennifer Tunnel, New Michael, NV 40793",
    //     "email": "uwalker@yahoo.com"
    //   },
    //   {
    //     "id": "E099",
    //     "name": "Peter Mcmahon DDS",
    //     "role": "Kitchen Staff",
    //     "password": "password99",
    //     "dob": "1996-02-28",
    //     "telephone": "0924827205",
    //     "gender": "Female",
    //     "address": "58277 Nathan Crossroad Suite 916, New Jennifer, MS 66497",
    //     "email": "villegasann@gmail.com"
    //   },
    //   {
    //     "id": "E100",
    //     "name": "Nathan Stout",
    //     "role": "Software Engineer",
    //     "password": "password100",
    //     "dob": "2003-09-13",
    //     "telephone": "2815312136",
    //     "gender": "Male",
    //     "address": "1172 Fry Mountain, East Brittany, TX 22428",
    //     "email": "cobbgregory@yahoo.com"
    //   }
    // ]
    const users: Prisma.UserCreateInput[] =
    [
      {
          "id": "E001",
          "name": "Jordan Martin",
          "role": "QA Engineer",
          "password": "password1",
          "dob": "1999-02-16",
          "telephone": "0860574627",
          "gender": "Male",
          "address": "5333 Park Ave, Cityville, ST 78381",
          "email": "jordanmartin1@sample.org",
          "salary": 500942
      },
      {
          "id": "E002",
          "name": "Alex Harris",
          "role": "Inventory Manager",
          "password": "password2",
          "dob": "1961-02-10",
          "telephone": "8314811835",
          "gender": "Female",
          "address": "7411 Cedar Ln, Cityville, ST 90186",
          "email": "alexharris2@testmail.com",
          "salary": 800458
      },
      {
          "id": "E003",
          "name": "Jordan Smith",
          "role": "QA Engineer",
          "password": "password3",
          "dob": "1961-03-20",
          "telephone": "4609253983",
          "gender": "Female",
          "address": "1191 Highland Ave, Cityville, ST 45177",
          "email": "jordansmith3@testmail.com",
          "salary": 698983
      },
      {
          "id": "E004",
          "name": "Taylor Martin",
          "role": "QA Engineer",
          "password": "password4",
          "dob": "1974-10-13",
          "telephone": "3393566574",
          "gender": "Female",
          "address": "5735 Cedar Ln, Cityville, ST 36927",
          "email": "taylormartin4@testmail.com",
          "salary": 738098
      },
      {
          "id": "E005",
          "name": "Reese Taylor",
          "role": "HR Manager",
          "password": "password5",
          "dob": "1988-08-16",
          "telephone": "0100391300",
          "gender": "Male",
          "address": "2046 Broadway, Cityville, ST 48474",
          "email": "reesetaylor5@example.com",
          "salary": 124946
      },
      {
          "id": "E006",
          "name": "Alex Thomas",
          "role": "Inventory Manager",
          "password": "password6",
          "dob": "1969-04-26",
          "telephone": "6521387348",
          "gender": "Male",
          "address": "9769 Elm St, Cityville, ST 83173",
          "email": "alexthomas6@example.com",
          "salary": 213269
      },
      {
          "id": "E007",
          "name": "Morgan Jackson",
          "role": "QA Engineer",
          "password": "password7",
          "dob": "1962-06-09",
          "telephone": "9874968834",
          "gender": "Male",
          "address": "9176 Maple Dr, Cityville, ST 77817",
          "email": "morganjackson7@demo.net",
          "salary": 1126943
      },
      {
          "id": "E008",
          "name": "Parker Martin",
          "role": "HR Manager",
          "password": "password8",
          "dob": "1970-07-24",
          "telephone": "7315458065",
          "gender": "Male",
          "address": "2690 Cedar Ln, Cityville, ST 32001",
          "email": "parkermartin8@demo.net",
          "salary": 703299
      },
      {
          "id": "E009",
          "name": "Cameron Anderson",
          "role": "Inventory Manager",
          "password": "password9",
          "dob": "1981-07-19",
          "telephone": "7000875282",
          "gender": "Male",
          "address": "9677 Sunset Blvd, Cityville, ST 79884",
          "email": "cameronanderson9@sample.org",
          "salary": 259416
      },
      {
          "id": "E010",
          "name": "Jordan Taylor",
          "role": "HR Manager",
          "password": "password10",
          "dob": "1990-04-10",
          "telephone": "2511376194",
          "gender": "Male",
          "address": "5770 Broadway, Cityville, ST 18666",
          "email": "jordantaylor10@sample.org",
          "salary": 632776
      },
      {
          "id": "E011",
          "name": "Cameron Harris",
          "role": "QA Engineer",
          "password": "password11",
          "dob": "1984-10-04",
          "telephone": "5129377829",
          "gender": "Female",
          "address": "8343 Sunset Blvd, Cityville, ST 60747",
          "email": "cameronharris11@sample.org",
          "salary": 1221026
      },
      {
          "id": "E012",
          "name": "Alex Jackson",
          "role": "Kitchen Staff",
          "password": "password12",
          "dob": "1965-04-15",
          "telephone": "7290141381",
          "gender": "Male",
          "address": "9064 Park Ave, Cityville, ST 88297",
          "email": "alexjackson12@sample.org",
          "salary": 27638
      },
      {
          "id": "E013",
          "name": "Morgan Thomas",
          "role": "HR Manager",
          "password": "password13",
          "dob": "1965-01-09",
          "telephone": "4499405473",
          "gender": "Female",
          "address": "9994 Main St, Cityville, ST 62526",
          "email": "morganthomas13@testmail.com",
          "salary": 417068
      },
      {
          "id": "E014",
          "name": "Parker Smith",
          "role": "Kitchen Staff",
          "password": "password14",
          "dob": "1980-08-22",
          "telephone": "7886443643",
          "gender": "Male",
          "address": "9051 Main St, Cityville, ST 50415",
          "email": "parkersmith14@example.com",
          "salary": 1079266
      },
      {
          "id": "E015",
          "name": "Morgan Harris",
          "role": "Inventory Manager",
          "password": "password15",
          "dob": "1996-01-24",
          "telephone": "0176453135",
          "gender": "Female",
          "address": "9954 Sunset Blvd, Cityville, ST 73704",
          "email": "morganharris15@sample.org",
          "salary": 504209
      },
      {
          "id": "E016",
          "name": "Jamie Jackson",
          "role": "Inventory Manager",
          "password": "password16",
          "dob": "1960-07-16",
          "telephone": "3653235115",
          "gender": "Male",
          "address": "2566 Maple Dr, Cityville, ST 13905",
          "email": "jamiejackson16@demo.net",
          "salary": 1190055
      },
      {
          "id": "E017",
          "name": "Jamie Harris",
          "role": "HR Manager",
          "password": "password17",
          "dob": "2002-09-19",
          "telephone": "6851013607",
          "gender": "Male",
          "address": "8542 Broadway, Cityville, ST 17698",
          "email": "jamieharris17@demo.net",
          "salary": 717209
      },
      {
          "id": "E018",
          "name": "Reese Jackson",
          "role": "Kitchen Staff",
          "password": "password18",
          "dob": "2001-02-17",
          "telephone": "1484664710",
          "gender": "Female",
          "address": "1301 Elm St, Cityville, ST 83528",
          "email": "reesejackson18@example.com",
          "salary": 795257
      },
      {
          "id": "E019",
          "name": "Cameron White",
          "role": "QA Engineer",
          "password": "password19",
          "dob": "1976-10-07",
          "telephone": "9712050934",
          "gender": "Female",
          "address": "8650 Main St, Cityville, ST 66608",
          "email": "cameronwhite19@demo.net",
          "salary": 453455
      },
      {
          "id": "E020",
          "name": "Casey Harris",
          "role": "QA Engineer",
          "password": "password20",
          "dob": "1966-09-12",
          "telephone": "5227872426",
          "gender": "Female",
          "address": "1189 Broadway, Cityville, ST 13173",
          "email": "caseyharris20@demo.net",
          "salary": 1238515
      },
      {
          "id": "E021",
          "name": "Jamie Jackson",
          "role": "HR Manager",
          "password": "password21",
          "dob": "1969-01-12",
          "telephone": "7383713239",
          "gender": "Female",
          "address": "4030 Broadway, Cityville, ST 85017",
          "email": "jamiejackson21@demo.net",
          "salary": 1218904
      },
      {
          "id": "E022",
          "name": "Morgan Martin",
          "role": "QA Engineer",
          "password": "password22",
          "dob": "1966-03-25",
          "telephone": "9308251973",
          "gender": "Female",
          "address": "3798 Broadway, Cityville, ST 48421",
          "email": "morganmartin22@example.com",
          "salary": 1311776
      },
      {
          "id": "E023",
          "name": "Robin Anderson",
          "role": "HR Manager",
          "password": "password23",
          "dob": "1977-06-17",
          "telephone": "3068815408",
          "gender": "Female",
          "address": "3769 Maple Dr, Cityville, ST 75412",
          "email": "robinanderson23@example.com",
          "salary": 1154602
      },
      {
          "id": "E024",
          "name": "Morgan Martin",
          "role": "Kitchen Staff",
          "password": "password24",
          "dob": "2002-01-24",
          "telephone": "5716427088",
          "gender": "Female",
          "address": "5068 Park Ave, Cityville, ST 50941",
          "email": "morganmartin24@sample.org",
          "salary": 293902
      },
      {
          "id": "E025",
          "name": "Morgan Jackson",
          "role": "QA Engineer",
          "password": "password25",
          "dob": "1995-02-16",
          "telephone": "8353787330",
          "gender": "Female",
          "address": "4256 Highland Ave, Cityville, ST 89540",
          "email": "morganjackson25@example.com",
          "salary": 1095908
      },
      {
          "id": "E026",
          "name": "Parker Thomas",
          "role": "QA Engineer",
          "password": "password26",
          "dob": "1993-02-19",
          "telephone": "9544791341",
          "gender": "Male",
          "address": "9184 Elm St, Cityville, ST 15196",
          "email": "parkerthomas26@testmail.com",
          "salary": 559677
      },
      {
          "id": "E027",
          "name": "Reese Smith",
          "role": "Kitchen Staff",
          "password": "password27",
          "dob": "1961-07-25",
          "telephone": "1486957080",
          "gender": "Male",
          "address": "8586 Sunset Blvd, Cityville, ST 63132",
          "email": "reesesmith27@sample.org",
          "salary": 474890
      },
      {
          "id": "E028",
          "name": "Cameron Taylor",
          "role": "Kitchen Staff",
          "password": "password28",
          "dob": "1995-03-09",
          "telephone": "5580929296",
          "gender": "Male",
          "address": "4492 Cedar Ln, Cityville, ST 81221",
          "email": "camerontaylor28@demo.net",
          "salary": 73499
      },
      {
          "id": "E029",
          "name": "Morgan Harris",
          "role": "Inventory Manager",
          "password": "password29",
          "dob": "1995-11-08",
          "telephone": "6658115529",
          "gender": "Female",
          "address": "8457 Elm St, Cityville, ST 29663",
          "email": "morganharris29@sample.org",
          "salary": 1312917
      },
      {
          "id": "E030",
          "name": "Alex Anderson",
          "role": "QA Engineer",
          "password": "password30",
          "dob": "1964-05-09",
          "telephone": "4492772111",
          "gender": "Female",
          "address": "4993 Broadway, Cityville, ST 65775",
          "email": "alexanderson30@sample.org",
          "salary": 111238
      },
      {
          "id": "E031",
          "name": "Robin Harris",
          "role": "Inventory Manager",
          "password": "password31",
          "dob": "1997-03-17",
          "telephone": "3682926638",
          "gender": "Male",
          "address": "9623 Sunset Blvd, Cityville, ST 35057",
          "email": "robinharris31@sample.org",
          "salary": 574991
      },
      {
          "id": "E032",
          "name": "Morgan Harris",
          "role": "Inventory Manager",
          "password": "password32",
          "dob": "1996-08-18",
          "telephone": "3744460002",
          "gender": "Female",
          "address": "857 Maple Dr, Cityville, ST 98162",
          "email": "morganharris32@example.com",
          "salary": 1201948
      },
      {
          "id": "E033",
          "name": "Casey Harris",
          "role": "Inventory Manager",
          "password": "password33",
          "dob": "1970-07-04",
          "telephone": "3025308419",
          "gender": "Female",
          "address": "1117 Elm St, Cityville, ST 53986",
          "email": "caseyharris33@sample.org",
          "salary": 517042
      },
      {
          "id": "E034",
          "name": "Alex Anderson",
          "role": "Inventory Manager",
          "password": "password34",
          "dob": "1996-08-07",
          "telephone": "9144054412",
          "gender": "Male",
          "address": "6076 Maple Dr, Cityville, ST 66349",
          "email": "alexanderson34@sample.org",
          "salary": 448386
      },
      {
          "id": "E035",
          "name": "Jamie Johnson",
          "role": "QA Engineer",
          "password": "password35",
          "dob": "1971-05-12",
          "telephone": "4110495888",
          "gender": "Female",
          "address": "3560 Park Ave, Cityville, ST 19164",
          "email": "jamiejohnson35@example.com",
          "salary": 677270
      },
      {
          "id": "E036",
          "name": "Taylor Johnson",
          "role": "HR Manager",
          "password": "password36",
          "dob": "1994-07-21",
          "telephone": "0883310375",
          "gender": "Male",
          "address": "4884 Maple Dr, Cityville, ST 15223",
          "email": "taylorjohnson36@example.com",
          "salary": 583494
      },
      {
          "id": "E037",
          "name": "Jordan Martin",
          "role": "Kitchen Staff",
          "password": "password37",
          "dob": "1979-05-17",
          "telephone": "3389876727",
          "gender": "Male",
          "address": "6973 Broadway, Cityville, ST 34349",
          "email": "jordanmartin37@demo.net",
          "salary": 434278
      },
      {
          "id": "E038",
          "name": "Reese Martin",
          "role": "QA Engineer",
          "password": "password38",
          "dob": "1996-03-21",
          "telephone": "1444469495",
          "gender": "Female",
          "address": "497 Main St, Cityville, ST 77957",
          "email": "reesemartin38@sample.org",
          "salary": 1159645
      },
      {
          "id": "E039",
          "name": "Jamie Brown",
          "role": "HR Manager",
          "password": "password39",
          "dob": "1998-11-05",
          "telephone": "1391440028",
          "gender": "Male",
          "address": "3133 Main St, Cityville, ST 21567",
          "email": "jamiebrown39@sample.org",
          "salary": 738821
      },
      {
          "id": "E040",
          "name": "Jamie Johnson",
          "role": "Inventory Manager",
          "password": "password40",
          "dob": "1990-06-16",
          "telephone": "0773814738",
          "gender": "Male",
          "address": "5105 Broadway, Cityville, ST 23986",
          "email": "jamiejohnson40@testmail.com",
          "salary": 692472
      },
      {
          "id": "E041",
          "name": "Jamie Smith",
          "role": "QA Engineer",
          "password": "password41",
          "dob": "1999-06-19",
          "telephone": "5245030248",
          "gender": "Male",
          "address": "8143 Highland Ave, Cityville, ST 86480",
          "email": "jamiesmith41@example.com",
          "salary": 235763
      },
      {
          "id": "E042",
          "name": "Casey Smith",
          "role": "Inventory Manager",
          "password": "password42",
          "dob": "1977-06-16",
          "telephone": "4111168006",
          "gender": "Female",
          "address": "164 Cedar Ln, Cityville, ST 45131",
          "email": "caseysmith42@example.com",
          "salary": 774595
      },
      {
          "id": "E043",
          "name": "Parker Thomas",
          "role": "HR Manager",
          "password": "password43",
          "dob": "1962-04-19",
          "telephone": "8774109070",
          "gender": "Male",
          "address": "6589 Maple Dr, Cityville, ST 70211",
          "email": "parkerthomas43@testmail.com",
          "salary": 1371784
      },
      {
          "id": "E044",
          "name": "Alex Jackson",
          "role": "Kitchen Staff",
          "password": "password44",
          "dob": "1972-09-28",
          "telephone": "8147295884",
          "gender": "Male",
          "address": "2565 Main St, Cityville, ST 12836",
          "email": "alexjackson44@demo.net",
          "salary": 102864
      },
      {
          "id": "E045",
          "name": "Reese Harris",
          "role": "QA Engineer",
          "password": "password45",
          "dob": "1988-08-09",
          "telephone": "7017664251",
          "gender": "Female",
          "address": "2960 Park Ave, Cityville, ST 50473",
          "email": "reeseharris45@example.com",
          "salary": 213225
      },
      {
          "id": "E046",
          "name": "Morgan Brown",
          "role": "QA Engineer",
          "password": "password46",
          "dob": "1971-02-03",
          "telephone": "7645292688",
          "gender": "Male",
          "address": "6578 Park Ave, Cityville, ST 81668",
          "email": "morganbrown46@example.com",
          "salary": 913118
      },
      {
          "id": "E047",
          "name": "Robin Thomas",
          "role": "QA Engineer",
          "password": "password47",
          "dob": "1970-04-21",
          "telephone": "1501145378",
          "gender": "Male",
          "address": "6925 Maple Dr, Cityville, ST 81435",
          "email": "robinthomas47@demo.net",
          "salary": 830001
      },
      {
          "id": "E048",
          "name": "Parker Jackson",
          "role": "QA Engineer",
          "password": "password48",
          "dob": "1972-04-10",
          "telephone": "1899546990",
          "gender": "Female",
          "address": "7665 Elm St, Cityville, ST 18707",
          "email": "parkerjackson48@example.com",
          "salary": 44719
      },
      {
          "id": "E049",
          "name": "Cameron Brown",
          "role": "QA Engineer",
          "password": "password49",
          "dob": "1972-09-05",
          "telephone": "7199325309",
          "gender": "Male",
          "address": "9549 Cedar Ln, Cityville, ST 64915",
          "email": "cameronbrown49@demo.net",
          "salary": 506071
      },
      {
          "id": "E050",
          "name": "Taylor White",
          "role": "Kitchen Staff",
          "password": "password50",
          "dob": "1991-03-14",
          "telephone": "8166495403",
          "gender": "Female",
          "address": "5009 Elm St, Cityville, ST 30165",
          "email": "taylorwhite50@demo.net",
          "salary": 439167
      },
      {
          "id": "E051",
          "name": "Jamie Thomas",
          "role": "QA Engineer",
          "password": "password51",
          "dob": "1970-01-20",
          "telephone": "7285146313",
          "gender": "Female",
          "address": "7730 Main St, Cityville, ST 22331",
          "email": "jamiethomas51@sample.org",
          "salary": 674331
      },
      {
          "id": "E052",
          "name": "Morgan Martin",
          "role": "QA Engineer",
          "password": "password52",
          "dob": "1989-04-02",
          "telephone": "8526316693",
          "gender": "Male",
          "address": "2283 Park Ave, Cityville, ST 30751",
          "email": "morganmartin52@testmail.com",
          "salary": 860094
      },
      {
          "id": "E053",
          "name": "Casey White",
          "role": "HR Manager",
          "password": "password53",
          "dob": "1983-07-26",
          "telephone": "6299049565",
          "gender": "Male",
          "address": "3531 Elm St, Cityville, ST 65385",
          "email": "caseywhite53@demo.net",
          "salary": 782492
      },
      {
          "id": "E054",
          "name": "Morgan White",
          "role": "Inventory Manager",
          "password": "password54",
          "dob": "1961-08-07",
          "telephone": "7472628162",
          "gender": "Male",
          "address": "7064 Elm St, Cityville, ST 13803",
          "email": "morganwhite54@testmail.com",
          "salary": 643543
      },
      {
          "id": "E055",
          "name": "Jamie Jackson",
          "role": "Kitchen Staff",
          "password": "password55",
          "dob": "1999-09-12",
          "telephone": "0802256761",
          "gender": "Female",
          "address": "2494 Sunset Blvd, Cityville, ST 30374",
          "email": "jamiejackson55@testmail.com",
          "salary": 166303
      },
      {
          "id": "E056",
          "name": "Jamie Smith",
          "role": "QA Engineer",
          "password": "password56",
          "dob": "1968-08-02",
          "telephone": "0076836168",
          "gender": "Male",
          "address": "1296 Maple Dr, Cityville, ST 28400",
          "email": "jamiesmith56@example.com",
          "salary": 11817
      },
      {
          "id": "E057",
          "name": "Jordan Anderson",
          "role": "HR Manager",
          "password": "password57",
          "dob": "1975-02-15",
          "telephone": "8701124954",
          "gender": "Female",
          "address": "6100 Highland Ave, Cityville, ST 15573",
          "email": "jordananderson57@testmail.com",
          "salary": 1065144
      },
      {
          "id": "E058",
          "name": "Jamie Jackson",
          "role": "HR Manager",
          "password": "password58",
          "dob": "1981-02-27",
          "telephone": "4893542790",
          "gender": "Female",
          "address": "8726 Cedar Ln, Cityville, ST 68325",
          "email": "jamiejackson58@testmail.com",
          "salary": 1386679
      },
      {
          "id": "E059",
          "name": "Reese Jackson",
          "role": "Inventory Manager",
          "password": "password59",
          "dob": "1973-11-12",
          "telephone": "2468750860",
          "gender": "Male",
          "address": "1848 Broadway, Cityville, ST 64170",
          "email": "reesejackson59@example.com",
          "salary": 672979
      },
      {
          "id": "E060",
          "name": "Jamie Harris",
          "role": "Kitchen Staff",
          "password": "password60",
          "dob": "1970-03-18",
          "telephone": "7580812381",
          "gender": "Male",
          "address": "8268 Cedar Ln, Cityville, ST 44505",
          "email": "jamieharris60@demo.net",
          "salary": 334372
      },
      {
          "id": "E061",
          "name": "Alex Thomas",
          "role": "Kitchen Staff",
          "password": "password61",
          "dob": "1967-04-20",
          "telephone": "2722060556",
          "gender": "Male",
          "address": "3629 Elm St, Cityville, ST 46228",
          "email": "alexthomas61@demo.net",
          "salary": 182209
      },
      {
          "id": "E062",
          "name": "Cameron Harris",
          "role": "HR Manager",
          "password": "password62",
          "dob": "1962-04-28",
          "telephone": "4547893910",
          "gender": "Female",
          "address": "2673 Maple Dr, Cityville, ST 10467",
          "email": "cameronharris62@testmail.com",
          "salary": 738768
      },
      {
          "id": "E063",
          "name": "Alex Smith",
          "role": "Kitchen Staff",
          "password": "password63",
          "dob": "1963-05-26",
          "telephone": "6139871987",
          "gender": "Male",
          "address": "288 Maple Dr, Cityville, ST 65837",
          "email": "alexsmith63@example.com",
          "salary": 710484
      },
      {
          "id": "E064",
          "name": "Cameron Jackson",
          "role": "Inventory Manager",
          "password": "password64",
          "dob": "1983-08-13",
          "telephone": "3551074080",
          "gender": "Female",
          "address": "9436 Cedar Ln, Cityville, ST 86341",
          "email": "cameronjackson64@testmail.com",
          "salary": 601043
      },
      {
          "id": "E065",
          "name": "Casey Smith",
          "role": "HR Manager",
          "password": "password65",
          "dob": "1970-08-09",
          "telephone": "0683812241",
          "gender": "Female",
          "address": "7416 Cedar Ln, Cityville, ST 63127",
          "email": "caseysmith65@sample.org",
          "salary": 606199
      },
      {
          "id": "E066",
          "name": "Alex Smith",
          "role": "Kitchen Staff",
          "password": "password66",
          "dob": "1985-05-17",
          "telephone": "3502556481",
          "gender": "Female",
          "address": "1055 Park Ave, Cityville, ST 73440",
          "email": "alexsmith66@demo.net",
          "salary": 910684
      },
      {
          "id": "E067",
          "name": "Alex Smith",
          "role": "HR Manager",
          "password": "password67",
          "dob": "1973-07-21",
          "telephone": "0548717152",
          "gender": "Female",
          "address": "2618 Broadway, Cityville, ST 78308",
          "email": "alexsmith67@demo.net",
          "salary": 1245863
      },
      {
          "id": "E068",
          "name": "Morgan Taylor",
          "role": "Kitchen Staff",
          "password": "password68",
          "dob": "1983-08-24",
          "telephone": "9275804976",
          "gender": "Male",
          "address": "8054 Sunset Blvd, Cityville, ST 21809",
          "email": "morgantaylor68@demo.net",
          "salary": 222033
      },
      {
          "id": "E069",
          "name": "Parker Smith",
          "role": "Inventory Manager",
          "password": "password69",
          "dob": "1979-03-10",
          "telephone": "2542574620",
          "gender": "Male",
          "address": "9252 Broadway, Cityville, ST 39094",
          "email": "parkersmith69@testmail.com",
          "salary": 947623
      },
      {
          "id": "E070",
          "name": "Parker Anderson",
          "role": "QA Engineer",
          "password": "password70",
          "dob": "1980-12-05",
          "telephone": "6628410658",
          "gender": "Female",
          "address": "841 Maple Dr, Cityville, ST 15580",
          "email": "parkeranderson70@testmail.com",
          "salary": 656802
      },
      {
          "id": "E071",
          "name": "Robin Thomas",
          "role": "HR Manager",
          "password": "password71",
          "dob": "2003-06-25",
          "telephone": "6562099677",
          "gender": "Female",
          "address": "3037 Main St, Cityville, ST 25280",
          "email": "robinthomas71@testmail.com",
          "salary": 61944
      },
      {
          "id": "E072",
          "name": "Morgan Johnson",
          "role": "Inventory Manager",
          "password": "password72",
          "dob": "1987-12-13",
          "telephone": "4803796428",
          "gender": "Male",
          "address": "4714 Main St, Cityville, ST 96484",
          "email": "morganjohnson72@demo.net",
          "salary": 1373302
      },
      {
          "id": "E073",
          "name": "Jamie Johnson",
          "role": "QA Engineer",
          "password": "password73",
          "dob": "1975-03-09",
          "telephone": "4250251443",
          "gender": "Female",
          "address": "4203 Main St, Cityville, ST 86413",
          "email": "jamiejohnson73@testmail.com",
          "salary": 424813
      },
      {
          "id": "E074",
          "name": "Taylor Taylor",
          "role": "Inventory Manager",
          "password": "password74",
          "dob": "1968-09-12",
          "telephone": "2119758727",
          "gender": "Male",
          "address": "134 Elm St, Cityville, ST 19771",
          "email": "taylortaylor74@sample.org",
          "salary": 831778
      },
      {
          "id": "E075",
          "name": "Jamie Taylor",
          "role": "Kitchen Staff",
          "password": "password75",
          "dob": "1988-03-13",
          "telephone": "0973343219",
          "gender": "Male",
          "address": "4344 Broadway, Cityville, ST 60587",
          "email": "jamietaylor75@testmail.com",
          "salary": 1037981
      },
      {
          "id": "E076",
          "name": "Cameron Martin",
          "role": "QA Engineer",
          "password": "password76",
          "dob": "1982-06-03",
          "telephone": "8746895548",
          "gender": "Male",
          "address": "9295 Broadway, Cityville, ST 71168",
          "email": "cameronmartin76@sample.org",
          "salary": 1310992
      },
      {
          "id": "E077",
          "name": "Reese Martin",
          "role": "QA Engineer",
          "password": "password77",
          "dob": "1970-05-18",
          "telephone": "5790401686",
          "gender": "Female",
          "address": "6713 Highland Ave, Cityville, ST 87609",
          "email": "reesemartin77@example.com",
          "salary": 184089
      },
      {
          "id": "E078",
          "name": "Parker Harris",
          "role": "Kitchen Staff",
          "password": "password78",
          "dob": "1975-01-01",
          "telephone": "4669074489",
          "gender": "Male",
          "address": "9979 Maple Dr, Cityville, ST 94120",
          "email": "parkerharris78@demo.net",
          "salary": 1069539
      },
      {
          "id": "E079",
          "name": "Jamie Smith",
          "role": "Inventory Manager",
          "password": "password79",
          "dob": "1961-01-03",
          "telephone": "0640469509",
          "gender": "Female",
          "address": "1952 Maple Dr, Cityville, ST 10582",
          "email": "jamiesmith79@example.com",
          "salary": 733016
      },
      {
          "id": "E080",
          "name": "Robin Martin",
          "role": "HR Manager",
          "password": "password80",
          "dob": "1969-08-06",
          "telephone": "3449661796",
          "gender": "Female",
          "address": "101 Cedar Ln, Cityville, ST 79982",
          "email": "robinmartin80@testmail.com",
          "salary": 421806
      },
      {
          "id": "E081",
          "name": "Taylor Harris",
          "role": "Inventory Manager",
          "password": "password81",
          "dob": "1990-02-23",
          "telephone": "6902816941",
          "gender": "Female",
          "address": "5519 Highland Ave, Cityville, ST 82762",
          "email": "taylorharris81@testmail.com",
          "salary": 1243458
      },
      {
          "id": "E082",
          "name": "Cameron Anderson",
          "role": "HR Manager",
          "password": "password82",
          "dob": "1974-01-11",
          "telephone": "0852668103",
          "gender": "Female",
          "address": "3999 Highland Ave, Cityville, ST 33597",
          "email": "cameronanderson82@demo.net",
          "salary": 218128
      },
      {
          "id": "E083",
          "name": "Jamie White",
          "role": "HR Manager",
          "password": "password83",
          "dob": "1988-02-20",
          "telephone": "2706055593",
          "gender": "Female",
          "address": "6187 Sunset Blvd, Cityville, ST 83489",
          "email": "jamiewhite83@sample.org",
          "salary": 1234396
      },
      {
          "id": "E084",
          "name": "Cameron Anderson",
          "role": "Kitchen Staff",
          "password": "password84",
          "dob": "1971-09-24",
          "telephone": "0574721340",
          "gender": "Male",
          "address": "1557 Highland Ave, Cityville, ST 26114",
          "email": "cameronanderson84@demo.net",
          "salary": 91410
      },
      {
          "id": "E085",
          "name": "Reese Smith",
          "role": "Inventory Manager",
          "password": "password85",
          "dob": "1967-12-08",
          "telephone": "6226916700",
          "gender": "Male",
          "address": "5521 Elm St, Cityville, ST 36914",
          "email": "reesesmith85@demo.net",
          "salary": 1449447
      },
      {
          "id": "E086",
          "name": "Alex Smith",
          "role": "HR Manager",
          "password": "password86",
          "dob": "1996-03-09",
          "telephone": "2201111788",
          "gender": "Male",
          "address": "4386 Elm St, Cityville, ST 68576",
          "email": "alexsmith86@example.com",
          "salary": 960132
      },
      {
          "id": "E087",
          "name": "Morgan Johnson",
          "role": "HR Manager",
          "password": "password87",
          "dob": "1989-08-21",
          "telephone": "7061722536",
          "gender": "Male",
          "address": "5489 Sunset Blvd, Cityville, ST 12326",
          "email": "morganjohnson87@testmail.com",
          "salary": 68707
      },
      {
          "id": "E088",
          "name": "Jordan Jackson",
          "role": "Kitchen Staff",
          "password": "password88",
          "dob": "1985-12-03",
          "telephone": "2916617393",
          "gender": "Male",
          "address": "1471 Park Ave, Cityville, ST 29193",
          "email": "jordanjackson88@example.com",
          "salary": 564810
      },
      {
          "id": "E089",
          "name": "Taylor White",
          "role": "QA Engineer",
          "password": "password89",
          "dob": "1970-11-23",
          "telephone": "5213179202",
          "gender": "Female",
          "address": "6099 Sunset Blvd, Cityville, ST 40905",
          "email": "taylorwhite89@testmail.com",
          "salary": 871084
      },
      {
          "id": "E090",
          "name": "Alex Martin",
          "role": "Kitchen Staff",
          "password": "password90",
          "dob": "1985-07-12",
          "telephone": "7928441758",
          "gender": "Female",
          "address": "8942 Sunset Blvd, Cityville, ST 68856",
          "email": "alexmartin90@sample.org",
          "salary": 1240551
      },
      {
          "id": "E091",
          "name": "Alex Smith",
          "role": "Inventory Manager",
          "password": "password91",
          "dob": "1986-05-15",
          "telephone": "3826004883",
          "gender": "Female",
          "address": "3320 Elm St, Cityville, ST 70327",
          "email": "alexsmith91@demo.net",
          "salary": 338226
      },
      {
          "id": "E092",
          "name": "Robin Jackson",
          "role": "QA Engineer",
          "password": "password92",
          "dob": "1965-05-07",
          "telephone": "5836221088",
          "gender": "Female",
          "address": "875 Sunset Blvd, Cityville, ST 13427",
          "email": "robinjackson92@testmail.com",
          "salary": 930176
      },
      {
          "id": "E093",
          "name": "Jordan Thomas",
          "role": "HR Manager",
          "password": "password93",
          "dob": "1973-07-19",
          "telephone": "0241905450",
          "gender": "Female",
          "address": "7339 Main St, Cityville, ST 54937",
          "email": "jordanthomas93@testmail.com",
          "salary": 1436788
      },
      {
          "id": "E094",
          "name": "Reese White",
          "role": "Inventory Manager",
          "password": "password94",
          "dob": "1991-12-12",
          "telephone": "9823819845",
          "gender": "Male",
          "address": "5363 Park Ave, Cityville, ST 84203",
          "email": "reesewhite94@demo.net",
          "salary": 637843
      },
      {
          "id": "E095",
          "name": "Cameron Taylor",
          "role": "QA Engineer",
          "password": "password95",
          "dob": "1993-10-10",
          "telephone": "1213641551",
          "gender": "Female",
          "address": "4831 Maple Dr, Cityville, ST 57440",
          "email": "camerontaylor95@example.com",
          "salary": 1171453
      },
      {
          "id": "E096",
          "name": "Reese Johnson",
          "role": "Kitchen Staff",
          "password": "password96",
          "dob": "1985-08-23",
          "telephone": "5612716250",
          "gender": "Female",
          "address": "9138 Elm St, Cityville, ST 54052",
          "email": "reesejohnson96@demo.net",
          "salary": 207626
      },
      {
          "id": "E097",
          "name": "Morgan Harris",
          "role": "QA Engineer",
          "password": "password97",
          "dob": "1974-05-15",
          "telephone": "5851721318",
          "gender": "Female",
          "address": "5938 Elm St, Cityville, ST 60469",
          "email": "morganharris97@example.com",
          "salary": 625825
      },
      {
          "id": "E098",
          "name": "Casey Johnson",
          "role": "QA Engineer",
          "password": "password98",
          "dob": "1995-02-21",
          "telephone": "0502829326",
          "gender": "Female",
          "address": "548 Broadway, Cityville, ST 16313",
          "email": "caseyjohnson98@testmail.com",
          "salary": 872873
      },
      {
          "id": "E099",
          "name": "Casey Harris",
          "role": "HR Manager",
          "password": "password99",
          "dob": "1964-07-19",
          "telephone": "1811935629",
          "gender": "Male",
          "address": "4900 Highland Ave, Cityville, ST 50564",
          "email": "caseyharris99@example.com",
          "salary": 714994
      },
      {
          "id": "E100",
          "name": "Casey White",
          "role": "Kitchen Staff",
          "password": "password100",
          "dob": "2002-05-24",
          "telephone": "2481216516",
          "gender": "Female",
          "address": "6626 Main St, Cityville, ST 79491",
          "email": "caseywhite100@example.com",
          "salary": 74852
      }
  ]


    // const users: Prisma.UserCreateInput[]=[
    //   {
    //     "id": "E001",
    //     "name": "Joseph Kim",
    //     "role": "Kitchen Staff",
    //     "password": "password1",
    //     "dob": "1983-02-15",
    //     "telephone": "4911249283",
    //     "salary":65000,
    //     "gender": "Female",
    //     "address": "435 Elizabeth Stravenue, Williamsland, CA 32888",
    //     "email": "christianmark@sanders-lopez.com"
    //   },
    //   {
    //     "id": "E002",
    //     "name": "Maria Terry",
    //     "role": "Inventory Manager",
    //     "password": "password2",
    //     "dob": "2001-04-12",
    //     "telephone": "7463087835",
    //     "salary":150000,
    //     "gender": "Female",
    //     "address": "3259 Kim Keys, West Charlotteborough, LA 26562",
    //     "email": "sandra21@francis.biz"
    //   },
    // ]

  try {
    for (const user of users) {
      await userService.create(user);
    }
    console.log('Users created successfully.');
  } catch (error) {
    console.error('Error creating users:', error);
  } finally {
    await databaseService.$disconnect();
  }
}

main();
