name: Docker Build

on: [pull_request, workflow_dispatch]

jobs:
  docker-production-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: mydatabase

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./server
          file: ./server/Dockerfile
          push: false
          tags: user/repository:latest

      - name: Run Docker Compose
        run: docker-compose -f ./server/docker-compose.yml up --build -d

      - name: Run  Few tests
        run: |
          docker-compose -f ./server/docker-compose.yml exec -T nestjs npm test -- --runInBand --forceExit \
            src/test/iot-hardware/iot-hardware-integration.service.spec.ts \
            src/test/iot-hardware/device-calibration.service.spec.ts \
            src/test/user-portal/user-fingerprint-management.service.spec.ts \
            src/test/iot-hardware/r307-sensor-functionality.service.spec.ts \
            src/test/iot-hardware/esp32-connectivity.service.spec.ts \
            src/core/user/user.controller.spec.ts \
            src/modules/meal/meal-selection.service.spec.ts \
            src/core/user/user.service.spec.ts \
            src/modules/ingredient/ingredient.controller.spec.ts

      - name: Down Docker Compose
        if: always()
        run: docker-compose -f ./server/docker-compose.yml down -v







